### PR TITLE
v1.2 - April 2021

### PR DESCRIPTION
**Pull request by stephpenn1**
# HectorUI v1.2

## Highlights:
- Improved site navigation
- New design layout to enhance user experience
- Added Home landing page

 

## Bug fixes:
- Fixed input issues when loading Hector core with multiple RCPs
- Fixed error with themes with loading graphs

HectorUI_HomePage
Screen Shot 2021-04-20 at 2 16 27 PM

### CODE REVIEW

**Review by crvernon — APPROVED** [review]
Changes look good.  I'll have additional comments to follow.

**Comment by crvernon** [comment]
@stephpenn1 please change the splash image to the new one in the README

**Comment by crvernon** [comment]
@zarrarkhan please work with @stephpenn1 to set up auto-deploy to pkg_down using GitHub actions for this PR so when this goes to main, we can have an auto rebuild of the docs.

**Comment by crvernon** [comment]
@stephpenn1 @zarrarkhan we should look into a deployment action to auto push to shinyapps.io

**Comment by crvernon** [comment]
Also in the future, we should get some GCIMS branding on there with a link to gcims.pnl.gov

**Comment by crvernon** [comment]
@stephpenn1 once you feel this is ready, go ahead and merge and dump this branch

**Comment by zarrarkhan** [comment]
> @zarrarkhan please work with @stephpenn1 to set up auto-deploy to pkg_down using GitHub actions for this PR so when this goes to main, we can have an auto rebuild of the docs.
@stephpenn1 take a look at this step-by-step guide I wrote about adding pkg_down to a repo as well as to github actions. https://docs.google.com/document/d/1kgTceyqSscc3LbvYLqxaDsG5L4IE7B4_5s2RJw1jyDo/edit#heading=h.dxlg60i83n6n

**Comment by zarrarkhan** [comment]
> @zarrarkhan please work with @stephpenn1 to set up auto-deploy to pkg_down using GitHub actions for this PR so when this goes to main, we can have an auto rebuild of the docs.

@stephpenn1 take a look at this step_by-step guide to adding pkgdown to a repo and github actions. https://docs.google.com/document/d/1kgTceyqSscc3LbvYLqxaDsG5L4IE7B4_5s2RJw1jyDo/edit#heading=h.dxlg60i83n6n

**Comment by zarrarkhan** [comment]
> @stephpenn1 @zarrarkhan we should look into a deployment action to auto push to shinyapps.io

Will try this on Argus but I think this should work once we setup an rsconnect TOKEN and SECRET:
```
- name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='username', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appName = 'appname')" 
```
from: https://community.rstudio.com/t/deploying-shiny-app-with-github-actions/78436

**Comment by crvernon** [comment]
> > @stephpenn1 @zarrarkhan we should look into a deployment action to auto push to shinyapps.io
> 
> Will try this on Argus but I think this should work once we setup an rsconnect TOKEN and SECRET:
> 
> ```
> - name: Push to shiny.io
>         run: |
>           Rscript -e "rsconnect::setAccountInfo(name='username', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
>           Rscript -e "rsconnect::deployApp(appName = 'appname')" 
> ```
> 
> from: https://community.rstudio.com/t/deploying-shiny-app-with-github-actions/78436

@stephpenn1 you can add the tokens to your repo based on the info I gave you for shinyapps the other day

**Pull request merged**
